Repository webuko/frontend, pull requests merged in 2021-05, with the labels that each got.

#14 Develop
  .devcontainer/devcontainer.json
  android/app/src/main/AndroidManifest.xml
  assets/images/house1.jpg
  assets/images/house2.jpeg
  assets/images/house3.jpeg
  assets/images/logo.png
  assets/images/name.png
  lib/HomeScreen.dart
  lib/main.dart
  lib/models/mockModel.dart
  pubspec.lock
  pubspec.yaml
  web/index.html
Labels: frontend

#16 Develop
  lib/main.dart
  pubspec.yaml
Labels: enhancement, frontend

#20 Feature/map/read api data
  .github/workflows/flutter-build-publish-web.yml
  android/app/build.gradle
  assets/marker.png
  lib/HomeScreen.dart
  lib/api/flatProvider.dart
  lib/main.dart
  lib/map.dart
  lib/models/mockModel.dart
  lib/models/place.dart
  lib/models/placeProvider.dart
  lib/screens/flat_detail_screen.dart
  lib/screens/home_screen.dart
  lib/widget/bottom_sheet_widget.dart
  pubspec.yaml
Labels: FlatDetailScreen, HomeScreen, enhancement, frontend

#22 #10: Created drawer for filterListings & pricePrediction
  lib/api/flatProvider.dart
  lib/map.dart
  lib/screens/flat_detail_screen.dart
  lib/screens/home_screen.dart
  lib/widget/bottom_sheet_widget_filter.dart
  lib/widget/bottom_sheet_widget_price_prediction.dart
  pubspec.yaml
Labels: FlatDetailScreen, HomeScreen, enhancement, frontend

#23 #21: pricePrediction implemented, small design improvements
  assets/marker.psd
  lib/api/flatProvider.dart
  lib/screens/home_screen.dart
  lib/widget/bottom_sheet_widget_filter.dart
  lib/widget/bottom_sheet_widget_price_prediction.dart
  pubspec.yaml
Labels: HomeScreen, frontend

#27 Feature/map/polygons
  analysis_options.yaml
  lib/api/flat_provider.dart
  lib/api/neigbourhood_provider.dart
  lib/gist/Gist.dart
  lib/main.dart
  lib/models/mockModel.dart
  lib/models/polygon_neighbourhood.dart
  lib/screens/flat_detail_screen.dart
  lib/screens/home_screen.dart
  lib/widget/bottom_sheet_widget_filter.dart
  lib/widget/bottom_sheet_widget_price_prediction.dart
  pubspec.yaml
Labels: enhancement, frontend

#28 Documentation and minor refactorings
  .gitignore
  assets/images/house1.jpg
  assets/images/house2.jpeg
  assets/images/house3.jpeg
  lib/api/flat_provider.dart
  lib/api/neigbourhood_provider.dart
  lib/map.dart
  lib/models/flat.dart
  lib/models/polygon_neighbourhood.dart
  lib/screens/flat_detail_screen.dart
  lib/screens/home_screen.dart
  lib/widget/bottom_sheet_widget_filter.dart
  lib/widget/bottom_sheet_widget_price_prediction.dart
  lib/widget/google_maps_widget.dart
  pubspec.yaml
  web/index.html
Labels: documentation

#30 #29: Parameterization of the backend host implemented
  lib/api/flat_provider.dart
  lib/api/neigbourhood_provider.dart
  lib/host.dart
Labels: enhancement, frontend

#31 Release 1.0
  .devcontainer/devcontainer.json
  .github/workflows/flutter-build-publish-web.yml
  .github/workflows/latest-publish.yaml
  .github/workflows/snapshot-publish.yaml
  .gitignore
  Dockerfile
  README.md
  analysis_options.yaml
  android/app/build.gradle
  assets/images/house1.jpg
  assets/images/house2.jpeg
  assets/images/house3.jpeg
  assets/marker.png
  assets/marker.psd
  docker-compose.yaml
  lib/HomeScreen.dart
  lib/api/flat_provider.dart
  lib/api/neigbourhood_provider.dart
  lib/gist/gist.dart
  lib/host.dart
  lib/main.dart
  lib/map.dart
  lib/models/flat.dart
  lib/models/mockModel.dart
  lib/models/place.dart
  lib/models/placeProvider.dart
  lib/models/polygon_neighbourhood.dart
  lib/screens/flat_detail_screen.dart
  lib/screens/home_screen.dart
  lib/widget/bottom_sheet_widget_filter.dart
  lib/widget/bottom_sheet_widget_price_prediction.dart
  lib/widget/google_maps_widget.dart
  pubspec.yaml
  web/favicon_house.png
  web/index.html
Labels: frontend
